version: "3"
services:
  client:
    build:
      context: ../.
      dockerfile: docker/Dockerfile.client.dev
    image: deathwish-client
    environment:
      - NODE_ENV=development
    volumes: # For webpack dev server to use our local files
      # We need to make docker share the shared node_modules
      # see https://www.youtube.com/watch?v=aYF90AKjVfY
      # https://github.com/benawad/fullstack-graphql-airbnb-clone/blob/10_docker/Dockerfile
      # https://stackoverflow.com/questions/50650191/yarn-workspaces-and-docker
      #
      # we might be better off using concurrently for now to bring up the server
      # and client together and only use docker to boot mongo
      - ./../node_modules:/usr/src/client/node_modules
      - ./../packages/deathwish-client:/usr/src/client
    ports:
      - "3999:3000" # For docker to know where to redirect HMR queries
  server:
    build:
      context: ../.
      dockerfile: docker/Dockerfile.server.dev
    image: deathwish-server
    environment:
      - NODE_ENV=development
    volumes:
      - ./../node_modules:/usr/src/server/node_modules
      - ./../packages/deathwish-server:/usr/src/server
    ports:
      - "4000"
